### ISSUE TITLE
get name function in Person.js

### ISSUE THREAD

**Issue by ghost** [timroes/angular-es6-sample#2]
In src/scripts/model/Person.js, why is `name getter` called as `get name`. Isn't `getName` the commonly used pattern?

Again, how will this method with spaces get invoked?

**Comment by timroes** [comment]
ES6 introduces getter and setter methods for properties. You just write `get foo()` or `set foo(val)` and these methods will be called automatically when accessing `obj.foo` in a reading or writing way. E.g. see here:

http://stackoverflow.com/questions/28222276/what-are-getters-and-setters-for-in-ecmascript-6-classes
